export const ROUTES = {
  main: '/',
  mintSelectToken: '/mint-select-token',
  mintSelectReceiver: '/mint-select-receiver',
  makeIOUToken1: '/make-iou-token-1',
  makeIOUToken2: '/make-iou-token-2',
  payoffSelectToken: '/payoff-select-token',
  payoffAndFeedback: '/payoff-and-feedback',
  stakeSelectToken: '/stake-select-token',
  stakeAddPair: '/stake-add-pair',
  stakeAddLiquidity: '/stake-add-liquidity',
  findBuyIOU: '/find-buy-iou',
  buyIOUSelect: '/buy-iou-select',
  buyIOU: '/buy-iou',
  selectDesiredIOUSwap: '/select-desired-iou-swap',
  swapSelectDesiredToken: '/swap-select-desired-token',
  swapSelectAvailableToken: '/swap-select-available-token',
};
